from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
import os
import sys
import uuid
from langchain_core.messages import HumanMessage

# Add project root to path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from agents.agents import app
from graph.lineage_graph import LineageGraph

api = Flask(__name__)
CORS(api)  # Enable CORS for all routes

# Store thread configs in memory for POC
thread_store = {}

@api.route('/health', methods=['GET'])
def health():
    return jsonify({"status": "healthy", "service": "XRS-Nexus Multi-Agent API"})

@api.route('/chat', methods=['POST'])
def chat():
    data = request.json
    user_message = data.get('message')
    thread_id = data.get('thread_id')
    
    # Handle HITL approval action from UI
    if data.get('action') == 'approve_correction':
        # Simulate approval logic
        # In a real app, we would resume the graph with the approved state
        return jsonify({
            "response": "Correction APPROVED. The system is applying the fix...",
            "agent": "system",
            "thread_id": thread_id
        })

    if not thread_id:
        thread_id = str(uuid.uuid4())
    
    config = {"configurable": {"thread_id": thread_id}}
    
    inputs = {"messages": [HumanMessage(content=user_message)]}
    
    try:
        # We invoke to get the final state
        result = app.invoke(inputs, config=config)
        last_message = result["messages"][-1]
        
        # Check if it's a HITL request (Dict with 'messages' key from hitl_node)
        # LangGraph returns the state, so we check if the last node output was from HITL
        response_text = ""
        is_hitl = False
        
        if isinstance(last_message, dict) and "messages" in last_message:
             # This handles the custom return from hitl_node
             response_text = last_message["messages"][0].content
             agent_name = "hitl_agent"
             is_hitl = True
        else:
            response_text = last_message.content
            agent_name = getattr(last_message, 'name', 'System')
            if "[HITL_REQUIRED]" in response_text:
                is_hitl = True

        return jsonify({
            "response": response_text,
            "agent": agent_name,
            "thread_id": thread_id,
            "requires_approval": is_hitl
        })
    except Exception as e:
        print(f"Error: {e}")
        return jsonify({"error": str(e)}), 500

@api.route('/lineage', methods=['GET'])
def get_lineage():
    # Return the Mermaid graph content
    try:
        # 1. Try to get from file (generated by scripts)
        if os.path.exists("lineage_graph.mmd"):
            with open("lineage_graph.mmd", "r") as f:
                content = f.read()
            return jsonify({"mermaid": content})
        
        # 2. Fallback: Generate a simple graph from the JSON logs
        from agents.tools import get_etl_lineage_logs
        logs = get_etl_lineage_logs.invoke({})
        
        # Conversion logic (simplified)
        # This is a fallback if the mmd file isn't there
        graph = "graph TD;\n"
        if "No ETL logs" in logs:
             graph += "Start --> End"
        else:
             # This is a string, we'd need to parse it back or read the file directly
             pass 
             
        return jsonify({"mermaid": graph if "Start --> End" not in graph else "graph TD;\nData_Source[Simulation Data] --> Memory --> SQLite"}), 200
    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5001))
    api.run(host='0.0.0.0', port=port, debug=True)
