from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
import os
import sys
import json
import uuid
from langchain_core.messages import HumanMessage

# Add project root to path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from agents.agents import app
from graph.lineage_graph import LineageGraph

api = Flask(__name__)
CORS(api)  # Enable CORS for all routes

# Store thread configs in memory for POC
thread_store = {}

@api.route('/health', methods=['GET'])
def health():
    return jsonify({"status": "healthy", "service": "XRS-Nexus Multi-Agent API"})

@api.route('/chat', methods=['POST'])
def chat():
    data = request.json
    user_message = data.get('message')
    thread_id = data.get('thread_id')
    
    # Handle HITL approval action from UI
    if data.get('action') == 'approve_correction':
        # Simulate approval logic
        # In a real app, we would resume the graph with the approved state
        return jsonify({
            "response": "Correction APPROVED. The system is applying the fix...",
            "agent": "system",
            "thread_id": thread_id
        })

    if not thread_id:
        thread_id = str(uuid.uuid4())
    
    config = {"configurable": {"thread_id": thread_id}}
    
    inputs = {"messages": [HumanMessage(content=user_message)]}
    
    try:
        # We invoke to get the final state
        result = app.invoke(inputs, config=config)
        last_message = result["messages"][-1]
        
        # Check if it's a HITL request (Dict with 'messages' key from hitl_node)
        # LangGraph returns the state, so we check if the last node output was from HITL
        response_text = ""
        is_hitl = False
        
        if isinstance(last_message, dict) and "messages" in last_message:
             # This handles the custom return from hitl_node
             response_text = last_message["messages"][0].content
             agent_name = "hitl_agent"
             is_hitl = True
        else:
            response_text = last_message.content
            agent_name = getattr(last_message, 'name', 'System')
            if "[HITL_REQUIRED]" in response_text:
                is_hitl = True

        return jsonify({
            "response": response_text,
            "agent": agent_name,
            "thread_id": thread_id,
            "requires_approval": is_hitl
        })
    except Exception as e:
        print(f"Error: {e}")
        return jsonify({"error": str(e)}), 500

@api.route('/lineage', methods=['GET'])
def get_lineage():
    # Return the Mermaid graph content
    try:
        # 1. Try to get from file (generated by scripts)
        if os.path.exists("lineage_graph.mmd"):
            with open("lineage_graph.mmd", "r") as f:
                content = f.read()
            return jsonify({"mermaid": content})
        
        # 2. Fallback: Parse the JSON logs directly
        log_path = "data/simulation/etl_lineage_log.json"
        if not os.path.exists(log_path):
             return jsonify({"mermaid": "graph TD;\nData_Source[Simulation Data] --> Memory --> SQLite"}), 200

        with open(log_path, 'r') as f:
            logs = json.load(f)
        
        # Convert JSON logs to Mermaid Graph
        graph = "graph TD;\n"
        graph += "    classDef file fill:#ffffff,stroke:#2563eb,stroke-width:2px,color:#1e293b;\n"
        graph += "    classDef db fill:#ffffff,stroke:#059669,stroke-width:2px,color:#1e293b;\n"
        graph += "    classDef memory fill:#ffffff,stroke:#9333ea,stroke-width:2px,stroke-dasharray: 5 5,color:#1e293b;\n"
        
        import re

        def clean_label(label):
            label = label.replace("file://data/simulation/", "📄 ")
            label = label.replace("sqlite://data/simulation/", "🗄️ ")
            label = label.replace("unstructured_data.xlsx/sheet/", "Excel: ")
            label = label.replace("structured_data.db/table/", "DB: ")
            label = label.replace("memory_dataframe_clean", "🧠 Cleaned DataFrame")
            label = label.replace("memory_dataframe", "🧠 Raw DataFrame")
            label = label.replace("discovery_registry", "🔍 Discovery Registry")
            return label.strip()

        # Deduplicate edges to keep graph clean
        seen_edges = set()

        for entry in logs:
            source = clean_label(entry['source'])
            target = clean_label(entry['target'])
            
            # Create safe IDs for Mermaid
            s_id = re.sub(r'[^a-zA-Z0-9]', '_', source)
            t_id = re.sub(r'[^a-zA-Z0-9]', '_', target)
            
            edge_key = f"{s_id}-{t_id}"
            if edge_key in seen_edges:
                continue
            seen_edges.add(edge_key)
            
            # Assign classes
            s_class = "file" if "📄" in source or "Excel" in source else "db" if "🗄️" in source or "DB" in source else "memory"
            t_class = "file" if "📄" in target or "Excel" in target else "db" if "🗄️" in target or "DB" in target else "memory"

            graph += f"    {s_id}[\"{source}\"]:::{s_class} --> {t_id}[\"{target}\"]:::{t_class};\n"
        
        return jsonify({"mermaid": graph})
    except Exception as e:
         return jsonify({"error": str(e), "mermaid": "graph TD;\nError[\"Error Loading Graph\"]"})

@api.route('/scan', methods=['POST'])
def scan_lineage():
    """Triggers a runtime scan of the data simulation folder."""
    try:
        # In a real app, this would trigger the actual agents.
        # For this POC, we re-run the ETL/Simulation logic or just return success
        # to simulate the "AI Scanning" delay.
        import time
        time.sleep(2) 
        return jsonify({"status": "success", "message": "Runtime Scan Complete. Lineage Updated."})
    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5001))
    api.run(host='0.0.0.0', port=port, debug=True)
