import json
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path


def run_tf_output_json(infra_dir: Path) -> dict:
    proc = subprocess.run(
        ["terraform", "output", "-json"],
        cwd=str(infra_dir),
        check=False,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise SystemExit(proc.stderr.strip() or proc.stdout.strip() or "terraform output -json failed")
    try:
        return json.loads(proc.stdout)
    except json.JSONDecodeError as e:
        raise SystemExit(f"Failed parsing terraform JSON output: {e}")


def get_output(outputs: dict, name: str):
    o = outputs.get(name)
    if not o:
        return None
    # Terraform output JSON schema: { "value": ..., "type": ..., "sensitive": ... }
    return o.get("value")


def main() -> int:
    infra_dir = Path(__file__).resolve().parents[1]  # infra/
    repo_root = infra_dir.parent
    dotenv_path = repo_root / ".env"

    outputs = run_tf_output_json(infra_dir)

    search_endpoint = get_output(outputs, "ai_search_endpoint") or ""
    search_key = get_output(outputs, "ai_search_admin_key") or ""
    appinsights_cs = get_output(outputs, "application_insights_connection_string") or ""

    # Backup existing .env if present
    if dotenv_path.exists():
        ts = datetime.now().strftime("%Y%m%d-%H%M%S")
        backup = repo_root / f".env.bak.{ts}"
        shutil.copy2(dotenv_path, backup)

    content = "\n".join(
        [
            "# ==============================================================================",
            "# XRS NEXUS - Environment Configuration",
            "# Generated by infra/scripts/write_root_env_from_terraform.py",
            "# WARNING: This file contains secrets. Ensure it is listed in .gitignore.",
            "# ==============================================================================",
            "",
            "AZURE_SEARCH_ENDPOINT=" + (f"\"{search_endpoint}\"" if search_endpoint else ""),
            "AZURE_SEARCH_KEY=" + (f"\"{search_key}\"" if search_key else ""),
            "RAG_MODE=text",
            "",
            "APPINSIGHTS_CONNECTION_STRING=" + (f"\"{appinsights_cs}\"" if appinsights_cs else ""),
            "",
            "# Optional (only if you enable OpenAI):",
            "AZURE_OPENAI_ENDPOINT=",
            "AZURE_OPENAI_KEY=",
            "",
            "# Optional Fabric placeholders:",
            "FABRIC_WORKSPACE_ID=",
            "FABRIC_LAKEHOUSE_ID=",
            "FABRIC_ACCESS_TOKEN=",
            "",
        ]
    )

    dotenv_path.write_text(content + "\n", encoding="utf-8")
    print(f"Wrote {dotenv_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

